# Generated by Django 5.2.10 on 2026-07-24 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plan_stripe_price_id_tenant_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBeverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_beverages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrinkNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drink_take_ml', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('serving_qty', models.FloatField()),
                ('serving_unit', models.CharField(max_length=50)),
                ('serving_weight_grams', models.FloatField()),
                ('sodium', models.CharField(blank=True, max_length=50, null=True)),
                ('fat', models.CharField(blank=True, max_length=50, null=True)),
                ('potassium', models.CharField(blank=True, max_length=50, null=True)),
                ('water_grams', models.FloatField()),
                ('water_fraction', models.FloatField(help_text='Water % of total weight')),
                ('calories', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('date', models.DateField()),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meal_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('serving_info', models.CharField(blank=True, max_length=100, null=True)),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom_food', models.BooleanField(default=False)),
                ('serving_qty', models.CharField(blank=True, max_length=24, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_weight_grams', models.CharField(blank=True, max_length=50, null=True)),
                ('saturated_fat', models.CharField(blank=True, max_length=50, null=True)),
                ('cholesterol', models.CharField(blank=True, max_length=50, null=True)),
                ('sodium', models.CharField(blank=True, max_length=50, null=True)),
                ('total_carbohydrate', models.CharField(blank=True, max_length=50, null=True)),
                ('dietary_fiber', models.CharField(blank=True, max_length=50, null=True)),
                ('sugars', models.CharField(blank=True, max_length=50, null=True)),
                ('calories', models.CharField(blank=True, max_length=50, null=True)),
                ('potassium', models.CharField(blank=True, max_length=50, null=True)),
                ('protein', models.CharField(blank=True, max_length=50, null=True)),
                ('fat', models.CharField(blank=True, max_length=50, null=True)),
                ('carbs', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=50, null=True)),
                ('locale', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('nix_item_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nix_brand_id', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_name_item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='nutritionX.meallogs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_intake_goal_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_goal_kcal', models.CharField(blank=True, max_length=100, null=True)),
                ('protein_goal_g', models.CharField(blank=True, max_length=100, null=True)),
                ('carbs_goal_g', models.CharField(blank=True, max_length=100, null=True)),
                ('fat_goal_g', models.CharField(blank=True, max_length=100, null=True)),
                ('base_water_intake_goal_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyNutritionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('water_consumed_ml', models.FloatField(default=0)),
                ('calories_consumed_kcal', models.FloatField(default=0)),
                ('protein_consumed_g', models.FloatField(default=0)),
                ('carbs_consumed_g', models.FloatField(default=0)),
                ('fat_consumed_g', models.FloatField(default=0)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='nutritionX.nutritiongoal')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount_ml', models.FloatField(default=0)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
