# Generated by Django 5.2.10 on 2026-08-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionX', '0001_initial'),
        ('tenants', '0006_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombeverage',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='dailynutritionprogress',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='drinknutrients',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='meallogs',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='nutritiongoal',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
    ]
