# Generated by Django 6.0.1 on 2026-01-23 21:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Unique feature identifier (e.g., 'max_members')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this feature')),
                ('data_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('string', 'String')], default='bool', help_text='Data type for feature value', max_length=20)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Plan name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing frequency', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this plan is publicly available')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('subdomain', models.SlugField(help_text="Unique subdomain (e.g., 'gym1' in gym1.example.com)", max_length=100, unique=True)),
                ('branding', models.JSONField(blank=True, default=dict, help_text='Custom branding configuration (logo, colors, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='active', help_text='Current subscription status', max_length=20)),
                ('started_at', models.DateTimeField(help_text='When subscription started')),
                ('ends_at', models.DateTimeField(blank=True, help_text='When subscription ends (null for ongoing)', null=True)),
                ('plan', models.ForeignKey(help_text='Subscribed plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.plan')),
                ('tenant', models.ForeignKey(help_text='Tenant with this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Subscription',
                'verbose_name_plural': 'Tenant Subscriptions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(help_text='Feature value (format depends on feature data_type)')),
                ('feature', models.ForeignKey(help_text='Feature being entitled', on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='tenants.feature')),
                ('plan', models.ForeignKey(help_text='Plan this entitlement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='tenants.plan')),
            ],
            options={
                'verbose_name': 'Plan Entitlement',
                'verbose_name_plural': 'Plan Entitlements',
                'ordering': ['plan', 'feature'],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='TenantEntitlementOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(help_text='Override value (format depends on feature data_type)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this override expires (null for permanent)', null=True)),
                ('feature', models.ForeignKey(help_text='Feature being overridden', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='tenants.feature')),
                ('tenant', models.ForeignKey(help_text='Tenant receiving the override', on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_overrides', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Entitlement Override',
                'verbose_name_plural': 'Tenant Entitlement Overrides',
                'ordering': ['tenant', 'feature'],
                'unique_together': {('tenant', 'feature')},
            },
        ),
    ]
