# Generated by Django 5.2.10 on 2026-02-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID (price_...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID (cus_...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID (sub_...)', max_length=255, null=True),
        ),
    ]
