# Generated by Django 5.2.10 on 2026-07-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plan_stripe_price_id_tenant_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Which tenant referred this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the free trial ends, if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='When subscription ends/renews', null=True),
        ),
    ]
