# Generated by Django 5.2.10 on 2026-07-29 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_referred_by_tenantsubscription_trial_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, help_text='The reward amount earned (e.g. commission)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('void', 'Void')], default='pending', help_text='Status of the reward payout', max_length=20)),
                ('referred_tenant', models.ForeignKey(help_text='The tenant who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_rewards', to='tenants.tenant')),
                ('referrer', models.ForeignKey(help_text='The tenant who referred and earned the reward', on_delete=django.db.models.deletion.CASCADE, related_name='earned_referral_rewards', to='tenants.tenant')),
                ('subscription', models.ForeignKey(help_text='The subscription that triggered this reward', on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='tenants.tenantsubscription')),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
                'ordering': ['-created_at'],
            },
        ),
    ]
