# Generated by Django 5.2.10 on 2026-08-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_referralreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Connect Account ID (acct_...)', max_length=255, null=True),
        ),
    ]
