# Generated by Django 5.2.10 on 2026-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Gym/Tenant logo image', null=True, upload_to='tenant_logos/'),
        ),
    ]
