upstream gym_backend {
    server web:8000;
}

server {
    listen 80;
    
    # 1. YOUR PUBLIC IP (Critical for accessing without a domain name)
    server_name 3.147.66.56 localhost 127.0.0.1;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    client_max_body_size 100M;

    location / {
        proxy_pass http://gym_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Static files - Served directly by Nginx
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }

    # Media files - Served directly by Nginx
    location /media/ {
        alias /app/mediafiles/;
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }
}