# Generated by Django 5.2.10 on 2026-07-24 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plan_stripe_price_id_tenant_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EveningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mood_after', models.CharField(blank=True, max_length=64, null=True)),
                ('highlight_1', models.TextField(blank=True, null=True)),
                ('highlight_2', models.TextField(blank=True, null=True)),
                ('highlight_3', models.TextField(blank=True, null=True)),
                ('lesson', models.TextField(blank=True, null=True)),
                ('reflection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evening', to='reflection_logger.dailyreflection')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_focus_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EveningFocusReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effort', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('improvement', models.TextField(blank=True, null=True)),
                ('evening_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_reflections', to='reflection_logger.eveningentry')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reflection_logger.focusoption')),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_start_date', models.DateField()),
                ('cycle_length_days', models.PositiveSmallIntegerField()),
                ('period_duration_days', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MorningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(blank=True, max_length=64, null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('affirmation', models.TextField(blank=True, null=True)),
                ('gratitude_1', models.TextField(blank=True, null=True)),
                ('gratitude_2', models.TextField(blank=True, null=True)),
                ('gratitude_3', models.TextField(blank=True, null=True)),
                ('reflection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning', to='reflection_logger.dailyreflection')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MorningFocusSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_plan', models.TextField(blank=True, null=True)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reflection_logger.focusoption')),
                ('morning_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_selections', to='reflection_logger.morningentry')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Symptom Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SymptomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reflection_logger.symptomcategory')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CycleDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('flow_intensity', models.IntegerField(choices=[(0, 'None'), (1, 'Spotting'), (2, 'Light'), (3, 'Medium'), (4, 'Heavy')], default=0)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_logs', to=settings.AUTH_USER_MODEL)),
                ('symptoms', models.ManyToManyField(blank=True, to='reflection_logger.symptomtag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='focusoption',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_focus'),
        ),
        migrations.AlterUniqueTogether(
            name='eveningfocusreflection',
            unique_together={('evening_entry', 'focus')},
        ),
        migrations.AlterUniqueTogether(
            name='morningfocusselection',
            unique_together={('morning_entry', 'focus')},
        ),
        migrations.AlterUniqueTogether(
            name='symptomtag',
            unique_together={('category', 'user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cycledailylog',
            unique_together={('user', 'date')},
        ),
    ]
