# Generated by Django 5.2.10 on 2026-08-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection_logger', '0001_initial'),
        ('tenants', '0006_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycledailylog',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='dailyreflection',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='eveningentry',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='eveningfocusreflection',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='focusoption',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='menstrualcycle',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='morningentry',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='morningfocusselection',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='symptomcategory',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='symptomtag',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
    ]
