# Generated by Django 5.2.10 on 2026-08-08 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.CharField(blank=True, default='Rx1', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAssessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_title', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_left_value', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_right_value', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_final_value', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_raw_value', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('user_level', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='client_assements.assessmentsession')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
