# Generated by Django 5.2.10 on 2026-08-03 23:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_referralreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Default platform cut percentage (e.g., 10.00 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='TenantPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount transferred to tenant', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(help_text='Stripe Charge ID or UUID', max_length=100, unique=True)),
                ('amount_gross', models.DecimalField(decimal_places=2, help_text='Total amount charged to client', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text="Platform's cut", max_digits=10)),
                ('amount_net', models.DecimalField(decimal_places=2, help_text='Amount owed to tenant', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund')], default='charge', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payout'), ('paid', 'Paid Out'), ('failed', 'Payout Failed')], default='pending', max_length=20)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.tenantpayout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(choices=[('plan_a', 'Plan A (Basic)'), ('plan_b', 'Plan B (Pro)'), ('plan_c', 'Plan C (Enterprise)')], default='plan_a', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'feature_name')},
            },
        ),
    ]
