# Generated by Django 5.2.10 on 2026-08-04 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0005_tenant_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable feature name shown to gym owners', max_length=150)),
                ('code', models.SlugField(help_text="Internal feature identifier (e.g. 'advanced_analytics')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the billing/upgrade page')),
                ('stripe_price_id', models.CharField(help_text="Stripe Price ID (price_...) for this feature's recurring charge", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive features are hidden from the checkout UI')),
            ],
            options={
                'verbose_name': 'Billing Feature',
                'verbose_name_plural': 'Billing Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('slug', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('custom', 'Custom')], help_text='Internal plan identifier', max_length=20, unique=True)),
                ('allowed_feature_count', models.IntegerField(blank=True, help_text='Required feature count for this plan: 0 = none, 3 = exactly 3, None = all, -1 = any (custom)', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether gym owners can self-select this plan')),
            ],
            options={
                'verbose_name': 'Billing Plan',
                'verbose_name_plural': 'Billing Plans',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='featuretoggle',
            options={'verbose_name': 'Feature Toggle (Legacy)', 'verbose_name_plural': 'Feature Toggles (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='tenantsubscription',
            options={'verbose_name': 'Tenant Subscription (Legacy)', 'verbose_name_plural': 'Tenant Subscriptions (Legacy)'},
        ),
        migrations.CreateModel(
            name='TenantBillingSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID (sub_...) created after payment', max_length=255, null=True, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID (cs_...) used to initiate payment', max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='incomplete', help_text='Current billing status', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='When the current billing period ends (populated by webhook)', null=True)),
                ('active_features', models.ManyToManyField(blank=True, help_text='The specific premium features unlocked for this tenant', related_name='subscriptions', to='payments.billingfeature')),
                ('billing_plan', models.ForeignKey(help_text='The plan tier this subscription belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='payments.billingplan')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Billing Subscription',
                'verbose_name_plural': 'Tenant Billing Subscriptions',
            },
        ),
    ]
