# Generated by Django 5.2.10 on 2026-08-04 19:29
"""
Data migration: seed the 4 BillingPlan rows.

allowed_feature_count semantics (see BillingPlan docstring):
  None  → Premium  (all features auto-included)
  0     → Free     (no features)
  3     → Basic    (exactly 3 features must be selected)
  -1    → Custom   (any count chosen by gym owner)
"""
import uuid
from django.db import migrations


def seed_billing_plans(apps, schema_editor):
    BillingPlan = apps.get_model("payments", "BillingPlan")

    plans = [
        {
            "id": uuid.uuid4(),
            "name": "Free",
            "slug": "free",
            "allowed_feature_count": 0,
            "is_public": True,
        },
        {
            "id": uuid.uuid4(),
            "name": "Basic",
            "slug": "basic",
            "allowed_feature_count": 3,
            "is_public": True,
        },
        {
            "id": uuid.uuid4(),
            "name": "Premium",
            "slug": "premium",
            "allowed_feature_count": None,  # All features
            "is_public": True,
        },
        {
            "id": uuid.uuid4(),
            "name": "Custom",
            "slug": "custom",
            "allowed_feature_count": -1,  # Any count
            "is_public": True,
        },
    ]

    for plan_data in plans:
        BillingPlan.objects.get_or_create(
            slug=plan_data["slug"],
            defaults={k: v for k, v in plan_data.items() if k != "slug"},
        )


def delete_billing_plans(apps, schema_editor):
    """Reverse: remove the seeded plans (only if they have no subscriptions)."""
    BillingPlan = apps.get_model("payments", "BillingPlan")
    BillingPlan.objects.filter(slug__in=["free", "basic", "premium", "custom"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_billing_models"),
    ]

    operations = [
        migrations.RunPython(seed_billing_plans, reverse_code=delete_billing_plans),
    ]
