# Generated by Django 5.2.10 on 2026-08-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_seed_billing_plans'),
        ('tenants', '0006_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='platformledger',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='platformledger',
            name='type',
            field=models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('sub', 'Tenant Subscription')], default='charge', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantbillingsubscription',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantpayout',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
    ]
