# Generated by Django 5.2.10 on 2026-08-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_featuretoggle_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingfeature',
            name='billing_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', help_text='Billing frequency for this feature', max_length=20),
        ),
        migrations.AddField(
            model_name='billingfeature',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Recurring price of the feature subscription', max_digits=10),
        ),
        migrations.AddField(
            model_name='billingfeature',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID for this feature', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingfeature',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text="Stripe Price ID (price_...) for this feature's recurring charge", max_length=255, null=True),
        ),
    ]
