# Generated by Django 5.2.10 on 2026-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_update_basic_plan_feature_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbillingsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Whether the Gym Admin has requested plan cancellation at the end of the billing period'),
        ),
    ]
