# Generated by Django 5.2.10 on 2026-09-17 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_tenantbillingsubscription_cancel_at_period_end"),
        ("tenants", "0006_tenant_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymFeatureEntitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Gym-level active status of this feature entitlement",
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this gym's feature access expires",
                        null=True,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="The feature being entitled to the gym",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_entitlements",
                        to="payments.billingfeature",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="The tenant billing subscription granting this entitlement",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_entitlements",
                        to="payments.tenantbillingsubscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym Feature Entitlement",
                "verbose_name_plural": "Gym Feature Entitlements",
                "unique_together": {("tenant", "feature")},
            },
        ),
    ]
