# Generated by Django 5.2.10 on 2026-07-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('gym_owner', 'Gym Owner'), ('gym_manager', 'Gym Manager'), ('front_desk', 'Front Desk'), ('trainer', 'Trainer'), ('client', 'Client')], db_index=True, default='client', max_length=20),
        ),
    ]
