# Generated by Django 5.2.10 on 2026-07-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_booking_checked_out_at_facilityaccesslog_payoutrun_and_more'),
        ('users', '0005_pendingregistration_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_location',
            field=models.ForeignKey(blank=True, help_text='The main location this client belongs to. Used for data isolation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_clients', to='scheduling.location'),
        ),
    ]
