# Generated by Django 5.2.10 on 2026-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_primary_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='level',
            field=models.CharField(choices=[('RX1', 'RX1'), ('RX2', 'RX2'), ('RX3', 'RX3')], default='RX1', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('RX1', 'RX1'), ('RX2', 'RX2'), ('RX3', 'RX3')], default='RX1', help_text="The client's RX level (RX1, RX2, or RX3)", max_length=10),
        ),
    ]
