# Generated by Django 5.2.10 on 2026-09-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pendingregistration_level_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Referral code used during registration', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique member referral code', max_length=30, null=True),
        ),
    ]
