# Generated by Django 5.2.10 on 2026-10-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0006_tenant_logo'),
        ('users', '0010_staffregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lead_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='lifecycle_status',
            field=models.CharField(choices=[('lead', 'Lead'), ('trial', 'Trial'), ('active', 'Active'), ('at_risk', 'At Risk'), ('inactive', 'Inactive'), ('churned', 'Churned')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, help_text='Last timestamp when client transitioned from inactive/churned back to active', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'role', 'lifecycle_status'], name='user_tenant_role_status_idx'),
        ),
    ]
