# Generated by Django 5.2.10 on 2026-10-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_converted_at_user_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, help_text='Primary assigned personal trainer or coach', limit_choices_to={'role__in': ['trainer', 'gym_owner', 'gym_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_client_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
