# Generated by Django 5.2.10 on 2026-09-01 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0010_package_assigned_by_package_is_complimentary'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProcessedRewardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='PROCESSED', max_length=30)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_reward_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processed Reward Event',
                'verbose_name_plural': 'Processed Reward Events',
            },
        ),
        migrations.CreateModel(
            name='RewardCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points_cost', models.PositiveIntegerField(help_text='Points required to redeem')),
                ('item_type', models.CharField(choices=[('MERCHANDISE', 'Merchandise / Physical Item'), ('DISCOUNT_CODE', 'Discount Voucher'), ('FREE_CLASS', 'Free Class Credit'), ('PACKAGE_CREDIT', 'Package Credit'), ('CUSTOM', 'Custom Reward')], default='MERCHANDISE', max_length=30)),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Available inventory count (null for unlimited)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('package_type', models.ForeignKey(blank=True, help_text='Optional link to PackageType for FREE_CLASS or PACKAGE_CREDIT redemptions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_catalog_items', to='scheduling.packagetype')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reward Catalog Item',
                'verbose_name_plural': 'Reward Catalog Items',
                'ordering': ['points_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Program name e.g. 'VIP Loyalty', 'Spring Streak'", max_length=150)),
                ('program_type', models.CharField(choices=[('loyalty', 'Evergreen Loyalty'), ('challenge', 'Time-bound Challenge'), ('streak', 'Streak & Consistency'), ('referral', 'Member Referral'), ('tiered_vip', 'Tiered VIP')], default='loyalty', help_text='Program archetype', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reward Program',
                'verbose_name_plural': 'Reward Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Fulfillment'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=20)),
                ('redemption_code', models.CharField(db_index=True, help_text='Unique voucher code shown to member and scanned/validated by front desk staff', max_length=50, unique=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='rewards.rewardcatalogitem')),
                ('fulfilled_by', models.ForeignKey(blank=True, help_text='Staff user who marked the reward fulfilled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_reward_redemptions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Redemption',
                'verbose_name_plural': 'Reward Redemptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable rule title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(db_index=True, help_text="Event identifier e.g. 'booking.attended', 'workout.completed'", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-incremented on rule configuration updates')),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text="Event payload filters e.g. {'class_category': 'strength'}")),
                ('conditions', models.JSONField(blank=True, default=list, help_text='List of condition objects for safe sandboxed evaluation')),
                ('actions', models.JSONField(default=list, help_text='List of action objects executed on condition match')),
                ('max_executions_per_user', models.PositiveIntegerField(blank=True, help_text='Total lifetime executions allowed per user (null = unlimited)', null=True)),
                ('max_executions_per_period', models.PositiveIntegerField(blank=True, help_text='Maximum executions within rolling window', null=True)),
                ('period_window_days', models.PositiveIntegerField(blank=True, help_text='Rolling window length in days for execution limit', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules evaluate first')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reward_rules', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(help_text='Parent reward program', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rewards.rewardprogram')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reward Rule',
                'verbose_name_plural': 'Reward Rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRuleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('trigger_config_snapshot', models.JSONField(default=dict)),
                ('conditions_snapshot', models.JSONField(default=list)),
                ('actions_snapshot', models.JSONField(default=list)),
                ('change_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_rule_version_snapshots', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rewards.rewardrule')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reward Rule Version',
                'verbose_name_plural': 'Reward Rule Versions',
                'ordering': ['rule', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Bronze, Silver, Gold, Platinum', max_length=100)),
                ('threshold_points', models.PositiveIntegerField(default=0, help_text='Lifetime points needed to reach this tier')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Point multiplier (e.g. 1.25 for 25% bonus)', max_digits=4)),
                ('perks_description', models.TextField(blank=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_associations', to='rewards.badge')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='rewards.rewardprogram')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reward Tier',
                'verbose_name_plural': 'Reward Tiers',
                'ordering': ['threshold_points'],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('rule_config_snapshot', models.JSONField(help_text='Immutable snapshot of the rule configuration at execution time')),
                ('action_type', models.CharField(max_length=50)),
                ('action_payload', models.JSONField()),
                ('result_status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='SUCCESS', max_length=20)),
                ('result_data', models.JSONField(default=dict)),
                ('milestone_key', models.CharField(blank=True, db_index=True, help_text="Deduplication key for milestone achievements e.g. 'milestone:attendance:10'", max_length=255, null=True)),
                ('event_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.processedrewardevent')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='rewards.rewardrule')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Transaction',
                'verbose_name_plural': 'Reward Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0, help_text='Current spendable points balance')),
                ('lifetime_earned', models.IntegerField(default=0, help_text='Total points earned all-time')),
                ('lifetime_redeemed', models.IntegerField(default=0, help_text='Total points redeemed all-time')),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_members', to='rewards.rewardtier')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Wallet',
                'verbose_name_plural': 'Reward Wallets',
            },
        ),
        migrations.CreateModel(
            name='RewardPointLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(help_text='Positive for credit/earn, negative for debit/redeem')),
                ('balance_after', models.IntegerField(help_text='Wallet balance snapshot immediately following this transaction')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn Points'), ('REDEEM', 'Redeem Points'), ('EXPIRE', 'Points Expired'), ('ADJUSTMENT', 'Manual Adjustment'), ('REVERSAL', 'Transaction Reversal')], default='EARN', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_point_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='rewards.rewardredemption')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='rewards.rewardtransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='rewards.rewardwallet')),
            ],
            options={
                'verbose_name': 'Reward Point Ledger Entry',
                'verbose_name_plural': 'Reward Point Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='rewards.badge')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to='rewards.rewardrule')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(help_text="e.g. 'attendance', 'workout', 'reflection'", max_length=50)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
            },
        ),
        migrations.AddIndex(
            model_name='processedrewardevent',
            index=models.Index(fields=['tenant', 'event_type', 'idempotency_key'], name='rewards_pro_tenant__9c4cb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processedrewardevent',
            unique_together={('tenant', 'event_type', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='rewardcatalogitem',
            index=models.Index(fields=['tenant', 'is_active'], name='rewards_rew_tenant__64a18e_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardprogram',
            index=models.Index(fields=['tenant', 'is_active', 'program_type'], name='rewards_rew_tenant__27ea00_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='rewards_rew_tenant__b7c7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['tenant', 'user', 'status'], name='rewards_rew_tenant__2407c4_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['tenant', 'event_type', 'status'], name='rewards_rew_tenant__f959ee_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrule',
            index=models.Index(fields=['tenant', 'program', 'status'], name='rewards_rew_tenant__d524bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rewardruleversion',
            unique_together={('rule', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='rewardtier',
            unique_together={('program', 'name')},
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['tenant', 'user', 'created_at'], name='rewards_rew_tenant__b61456_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['tenant', 'rule', 'created_at'], name='rewards_rew_tenant__297499_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['tenant', 'rule', 'milestone_key'], name='rewards_rew_tenant__9c0493_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardwallet',
            index=models.Index(fields=['tenant', 'user'], name='rewards_rew_tenant__1cded6_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardwallet',
            index=models.Index(fields=['tenant', 'balance'], name='rewards_rew_tenant__3bea35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rewardwallet',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddIndex(
            model_name='rewardpointledger',
            index=models.Index(fields=['tenant', 'user', 'created_at'], name='rewards_rew_tenant__b5828b_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardpointledger',
            index=models.Index(fields=['wallet', 'created_at'], name='rewards_rew_wallet__f52fa2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('tenant', 'user', 'badge')},
        ),
        migrations.AlterUniqueTogether(
            name='userstreak',
            unique_together={('tenant', 'user', 'activity_type')},
        ),
    ]
