# Generated by Django 5.2.10 on 2026-09-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        ('tenants', '0006_tenant_logo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rewardprogram',
            name='rewards_rew_tenant__27ea00_idx',
        ),
        migrations.RemoveField(
            model_name='rewardprogram',
            name='is_active',
        ),
        migrations.AddField(
            model_name='rewardprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rewardprogram',
            index=models.Index(fields=['tenant', 'status', 'program_type'], name='rewards_rew_tenant__5bda0e_idx'),
        ),
    ]
