# Generated by Django 5.2.10 on 2026-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_remove_rewardprogram_rewards_rew_tenant__27ea00_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Badge graphic/icon image file upload', null=True, upload_to='badges/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_url',
            field=models.URLField(blank=True, help_text='External URL or auto-populated from image upload', max_length=500, null=True),
        ),
    ]
