# Generated by Django 5.2.10 on 2026-09-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_badge_image_alter_badge_icon_url'),
        ('scheduling', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcatalogitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Reward item image graphic upload', null=True, upload_to='catalog/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='granted_package',
            field=models.ForeignKey(blank=True, help_text='Package granted to the member if catalog item is a package credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reward_redemptions', to='scheduling.package'),
        ),
        migrations.AlterField(
            model_name='rewardcatalogitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL or auto-populated from image upload', max_length=500, null=True),
        ),
    ]
