# Generated by Django 5.2.10 on 2026-09-18 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_rewardcatalogitem_image_and_more'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcatalogitem',
            name='item_type',
            field=models.CharField(choices=[('MERCHANDISE', 'Merchandise / Physical Item'), ('DISCOUNT_CODE', 'Discount Voucher'), ('FREE_CLASS', 'Free Class Credit'), ('PACKAGE_CREDIT', 'Package Credit'), ('FREE_PACKAGE', 'Free Package'), ('CUSTOM', 'Custom Reward'), ('CUSTOM_REWARD', 'Custom Reward')], default='MERCHANDISE', max_length=30),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='activity_type',
            field=models.CharField(help_text="e.g. 'attendance', 'workout', 'reflection', 'nutrition'", max_length=50),
        ),
        migrations.CreateModel(
            name='ClientReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee_email', models.EmailField(blank=True, db_index=True, help_text='Invited referee email address before registration', max_length=254, null=True)),
                ('referral_code', models.CharField(db_index=True, help_text='Referral code used for this referral', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Registration'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('referee', models.ForeignKey(blank=True, help_text='Referred member once registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='Member who shared the referral code/link', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Client Referral',
                'verbose_name_plural': 'Client Referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'referral_code'], name='rewards_cli_tenant__5a28b8_idx'), models.Index(fields=['tenant', 'referee'], name='rewards_cli_tenant__ed1fe8_idx'), models.Index(fields=['tenant', 'referee_email'], name='rewards_cli_tenant__91adf9_idx'), models.Index(fields=['tenant', 'status'], name='rewards_cli_tenant__313cc4_idx')],
            },
        ),
    ]
