# Generated by Django 5.2.10 on 2026-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0004_rewardcatalogitem_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardcatalogitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("MERCHANDISE", "Merchandise / Physical Item"),
                    ("DISCOUNT_CODE", "Discount Voucher"),
                    ("FREE_CLASS", "Free Class Credit"),
                    ("PACKAGE_CREDIT", "Package Credit"),
                    ("FREE_PACKAGE", "Free Package"),
                    ("CUSTOM", "Custom Reward"),
                    ("CUSTOM_REWARD", "Custom Reward"),
                ],
                default="MERCHANDISE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userstreak",
            name="activity_type",
            field=models.CharField(
                help_text="e.g. 'attendance', 'workout', 'reflection', 'nutrition'",
                max_length=50,
            ),
        ),
    ]
