# Generated by Django 5.2.10 on 2026-09-17 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0005_alter_rewardcatalogitem_item_type_and_more"),
        ("tenants", "0006_tenant_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referral_code",
                    models.CharField(
                        db_index=True, help_text="The referral code used", max_length=50
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CODE", "Referral Code"),
                            ("LINK", "Referral Link / Deep-Link"),
                        ],
                        default="CODE",
                        help_text="Whether completed via direct in-app code or universal referral link",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                ("points_awarded_referrer", models.PositiveIntegerField(default=0)),
                ("points_awarded_referee", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "referee",
                    models.ForeignKey(
                        help_text="The newly referred client",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        help_text="The existing gym client who shared their referral code/link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Referral",
                "verbose_name_plural": "Client Referrals",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "referral_code"],
                        name="rewards_cli_tenant__5a28b8_idx",
                    ),
                    models.Index(
                        fields=["tenant", "referrer"],
                        name="rewards_cli_tenant__30ea3b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="rewards_cli_tenant__313cc4_idx",
                    ),
                ],
                "unique_together": {("tenant", "referee")},
            },
        ),
    ]
