# Generated by Django 5.2.10 on 2026-08-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_booking_checked_out_at_facilityaccesslog_payoutrun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformledger',
            name='payout_run',
        ),
        migrations.RemoveField(
            model_name='platformledger',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='platformledger',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='PayoutRun',
        ),
        migrations.DeleteModel(
            name='PlatformLedger',
        ),
    ]
