# Generated by Django 5.2.10 on 2026-08-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_platformledger_payout_run_and_more'),
        ('tenants', '0006_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='classtemplate',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='facilityaccesslog',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='package',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='staffclientassignment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stafflocation',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='substituterequest',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
    ]
