# Generated by Django 5.2.10 on 2026-08-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_appointment_tenant_alter_booking_tenant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
