# Generated by Django 5.2.10 on 2026-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Whether the client has requested cancellation at the end of the billing period'),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='active', help_text='Subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID (sub_...) for the package', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='billing_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing frequency for the package subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this package is active and purchaseable'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID on the Platform account', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID on the Platform account', max_length=255, null=True),
        ),
    ]
