# Generated by Django 5.2.10 on 2026-08-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_package_cancel_at_period_end_package_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the package at the time of purchase', max_digits=10, null=True),
        ),
    ]
