# Generated by Django 5.2.10 on 2026-08-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_backfill_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='cutoff_hours',
            field=models.PositiveIntegerField(default=12, help_text='Cancel window cutoff in hours'),
        ),
    ]
