# Generated by Django 5.2.10 on 2026-08-31 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_cancellationpolicy_cutoff_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Staff or Admin who manually assigned this package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='is_complimentary',
            field=models.BooleanField(default=False, help_text='Whether this package was granted as a free/complimentary package by gym staff'),
        ),
    ]
