# Generated by Django 5.2.10 on 2026-09-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0010_package_assigned_by_package_is_complimentary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("checked_in", "Checked In"),
                    ("attended", "Attended"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
    ]
