# Generated by Django 5.2.10 on 2026-09-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='grant_source',
            field=models.CharField(
                choices=[
                    ('PURCHASE', 'Direct Purchase / Stripe Subscription'),
                    ('MANUAL_COMPLIMENTARY', 'Manual Staff/Admin Complimentary Assignment'),
                    ('REWARD_RULE', 'Reward Rule Trigger'),
                    ('REWARD_REDEMPTION', 'Reward Store Redemption'),
                    ('SYSTEM', 'System / Other'),
                ],
                default='PURCHASE',
                help_text='Origin source of the package grant',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_complimentary',
            field=models.BooleanField(
                default=False,
                help_text='Whether this package was granted as a free/complimentary package manually by gym staff/admin',
            ),
        ),
    ]
