# Generated by Django 5.2.10 on 2026-09-15 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0012_package_grant_source"),
        ("tenants", "0006_tenant_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("grid_rows", models.PositiveSmallIntegerField()),
                ("grid_cols", models.PositiveSmallIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row", models.PositiveSmallIntegerField()),
                ("col", models.PositiveSmallIntegerField()),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Stable sequential number per spot type within layout"
                    ),
                ),
                ("label", models.CharField(editable=False, max_length=16)),
                (
                    "is_blocked",
                    models.BooleanField(default=False, help_text="Layout-level block"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpotType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "prefix",
                    models.CharField(
                        help_text="Prefix for spot labels, e.g. 'B' -> B1, B2",
                        max_length=6,
                    ),
                ),
                ("is_bookable", models.BooleanField(default=True)),
                ("color", models.CharField(default="#6366F1", max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classsession",
            name="blocked_spots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of spot IDs blocked for this occurrence",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="layout_version",
            field=models.PositiveIntegerField(
                blank=True, help_text="Pinned layout version snapshot", null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="default_capacity",
            field=models.PositiveIntegerField(
                default=0, help_text="Default class capacity fallback"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("class", "Class"),
                    ("appointment", "Appointment"),
                    ("facility", "Facility"),
                ],
                default="class",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("checked_in", "Checked In"),
                    ("attended", "Attended"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                    ("unassigned", "Unassigned"),
                    ("waitlisted", "Waitlisted"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(
                default=0, help_text="Configured or default room capacity"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["location", "is_deleted"], name="scheduling__locatio_600b92_idx"
            ),
        ),
        migrations.AddField(
            model_name="roomlayout",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layouts",
                to="scheduling.room",
            ),
        ),
        migrations.AddField(
            model_name="roomlayout",
            name="tenant",
            field=models.ForeignKey(
                help_text="The tenant this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="layout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="scheduling.roomlayout",
            ),
        ),
        migrations.AddField(
            model_name="spot",
            name="layout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spots",
                to="scheduling.roomlayout",
            ),
        ),
        migrations.AddField(
            model_name="spot",
            name="tenant",
            field=models.ForeignKey(
                help_text="The tenant this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="spot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="scheduling.spot",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("spot__isnull", False), ("status", "booked")),
                fields=("session", "spot"),
                name="unique_active_spot_booking",
            ),
        ),
        migrations.AddField(
            model_name="spottype",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spot_types",
                to="scheduling.location",
            ),
        ),
        migrations.AddField(
            model_name="spottype",
            name="tenant",
            field=models.ForeignKey(
                help_text="The tenant this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="spot",
            name="spot_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spots",
                to="scheduling.spottype",
            ),
        ),
        migrations.AddIndex(
            model_name="roomlayout",
            index=models.Index(
                fields=["room", "is_deleted"], name="scheduling__room_id_fe12da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spottype",
            unique_together={("location", "name")},
        ),
        migrations.AddIndex(
            model_name="spot",
            index=models.Index(
                fields=["layout", "row", "col"], name="scheduling__layout__0c56fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spot",
            unique_together={
                ("layout", "row", "col"),
                ("layout", "spot_type", "number"),
            },
        ),
    ]
