# Generated by Django 5.2.10 on 2026-09-19 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_roomlayout_spot_spottype_booking_is_guest_and_more'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBookingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('join_mode', models.CharField(default='physical', help_text="Preferred attendance mode: 'physical', 'remote', etc.", max_length=50)),
                ('virtual_coach', models.CharField(blank=True, default='', help_text="Preferred coach mode (e.g. 'virtual', 'in_person')", max_length=100)),
                ('music_preference', models.CharField(blank=True, default='', help_text="Preferred music genre/station (e.g. 'Chill Hop', 'Upbeat EDM')", max_length=100)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_preferences', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Client Booking Preference',
                'verbose_name_plural': 'Client Booking Preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
