# Generated by Django 5.2.10 on 2026-09-22 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_clientbookingpreference'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('bootcamp', 'Bootcamp'), ('seminar', 'Seminar'), ('retreat', 'Retreat'), ('certification', 'Certification'), ('masterclass', 'Masterclass'), ('community', 'Community Event')], default='workshop', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('event_type', models.CharField(choices=[('single', 'Single Session'), ('series', 'Multi-Session Series')], default='single', max_length=20)),
                ('enrollment_type', models.CharField(choices=[('entire_series', 'Entire Series Only'), ('drop_in_allowed', 'Drop-in Allowed')], default='entire_series', max_length=20)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of attendees')),
                ('waitlist_capacity', models.PositiveIntegerField(default=0, help_text='Maximum waitlist size')),
                ('is_free', models.BooleanField(default=False, help_text='True if free event; False if requires active client pass')),
                ('credits_required', models.PositiveIntegerField(default=1, help_text='Number of pass credits required if paid')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='published', max_length=20)),
                ('cancellation_cutoff_hours', models.PositiveIntegerField(default=24, help_text='Hours before start eligible for pass credit refund')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('assistant_instructors', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['trainer', 'gym_owner', 'gym_manager']}, related_name='assisted_events', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduling.location')),
                ('primary_instructor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['trainer', 'gym_owner', 'gym_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_events', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scheduling.room')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.event')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['trainer', 'gym_owner', 'gym_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sessions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sessions', to='scheduling.room')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['session_number', 'start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='registered', max_length=20)),
                ('pricing_type', models.CharField(choices=[('free', 'Free Event'), ('pass', 'Client Pass Credit'), ('complimentary', 'Staff Complimentary')], default='pass', max_length=20)),
                ('credits_deducted', models.PositiveIntegerField(default=0)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Special instructions, dietary restrictions, emergency contact')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_enrollments', to=settings.AUTH_USER_MODEL)),
                ('credit_source', models.ForeignKey(blank=True, help_text='The client pass instance from which credit was deducted (if paid)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_enrollments', to='scheduling.package')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scheduling.event')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('attended_sessions', models.ManyToManyField(blank=True, help_text='Track session-by-session attendance for multi-day workshops', related_name='attended_enrollments', to='scheduling.eventsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location', 'status', 'start_at'], name='scheduling__locatio_fc71db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventenrollment',
            unique_together={('event', 'client')},
        ),
    ]
