# Generated by Django 5.2.10 on 2026-10-06 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_appointment_credits_used_booking_credits_used_and_more'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_late_cancel',
            field=models.BooleanField(default=False, help_text='True if cancelled after late cancellation cutoff window'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_credits_allocated',
            field=models.PositiveIntegerField(blank=True, help_text='Frozen snapshot of total credits granted upon purchase/assignment', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='scheduling.package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='scheduling.packagetype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('past_due', 'Past Due')], default='completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='sched_bk_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status', 'checked_in_at'], name='sched_bk_client_attend_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session', 'status'], name='sched_bk_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityaccesslog',
            index=models.Index(fields=['tenant', 'checked_in_at'], name='sched_fac_tenant_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityaccesslog',
            index=models.Index(fields=['client', 'checked_in_at'], name='sched_fac_client_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tenant', 'status', 'expires_at'], name='sched_pkg_tenant_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='sched_pay_tenant_date_idx'),
        ),
    ]
