# Generated by Django 5.2.10 on 2026-10-06 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_backfill_retention_schema'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_show_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when booking was marked as no_show', null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'checked_in_at'], name='sched_bk_tenant_checkin_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'cancelled_at'], name='sched_bk_tenant_cancel_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['tenant', 'start_at', 'status'], name='sched_sess_tenant_start_idx'),
        ),
    ]
