# Generated by Django 5.2.10 on 2026-10-06 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRetentionMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_visit_at', models.DateTimeField(blank=True, null=True)),
                ('second_visit_at', models.DateTimeField(blank=True, null=True)),
                ('last_visit_at', models.DateTimeField(blank=True, help_text='Max of attended/checked-in Booking and FacilityAccessLog.checked_in_at', null=True)),
                ('last_booking_at', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_visit', models.PositiveIntegerField(blank=True, null=True)),
                ('visits_last_7d', models.PositiveIntegerField(default=0)),
                ('visits_last_30d', models.PositiveIntegerField(default=0)),
                ('visits_prev_30d', models.PositiveIntegerField(default=0, help_text='Visits between day -60 and day -31 for trend/velocity comparison')),
                ('visits_last_90d', models.PositiveIntegerField(default=0)),
                ('visit_frequency_weekly_30d', models.DecimalField(decimal_places=2, default=0.0, help_text='visits_last_30d / 4.28', max_digits=5)),
                ('attendance_trend', models.CharField(choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('declining', 'Declining'), ('inactive', 'Inactive')], default='stable', max_length=20)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_attended_classes', models.PositiveIntegerField(default=0)),
                ('total_facility_checkins', models.PositiveIntegerField(default=0)),
                ('total_cancellations', models.PositiveIntegerField(default=0)),
                ('total_late_cancellations', models.PositiveIntegerField(default=0)),
                ('total_no_shows', models.PositiveIntegerField(default=0)),
                ('booking_to_attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('no_show_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active_packages_count', models.PositiveIntegerField(default=0)),
                ('total_credits_remaining', models.PositiveIntegerField(default=0)),
                ('credit_utilization_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nearest_package_expiry_at', models.DateTimeField(blank=True, null=True)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('churn_risk_score', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_metrics', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Client Retention Metrics',
                'verbose_name_plural': 'Client Retention Metrics',
                'indexes': [models.Index(fields=['tenant', 'risk_level', 'days_since_last_visit'], name='ret_metric_tenant_risk_idx'), models.Index(fields=['tenant', 'churn_risk_score'], name='ret_metric_tenant_score_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('filter_criteria', models.JSONField(default=dict, help_text='JSON filter rules: lifecycle_status, days_inactive_gte, tags, risk_level, expiring_within_days, unused_credits_gte, assigned_trainer_id, etc.')),
                ('is_system_preset', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_segments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Saved Segment',
                'verbose_name_plural': 'Saved Segments',
                'ordering': ['-is_system_preset', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_system_preset'], name='ret_seg_tenant_preset_idx')],
            },
        ),
    ]
