# Generated by Django 5.2.10 on 2026-10-06 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0001_initial'),
        ('tenants', '0006_tenant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRetentionDailySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_active_members', models.PositiveIntegerField(default=0)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('total_trials', models.PositiveIntegerField(default=0)),
                ('total_at_risk', models.PositiveIntegerField(default=0)),
                ('total_inactive', models.PositiveIntegerField(default=0)),
                ('total_churned', models.PositiveIntegerField(default=0)),
                ('reactivated_last_30d', models.PositiveIntegerField(default=0)),
                ('avg_visit_frequency', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('churn_rate_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('retention_rate_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attended_today', models.PositiveIntegerField(default=0)),
                ('cancellations_today', models.PositiveIntegerField(default=0)),
                ('no_shows_today', models.PositiveIntegerField(default=0)),
                ('expiring_packages_next_7d', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Retention Daily Snapshot',
                'verbose_name_plural': 'Tenant Retention Daily Snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['tenant', 'snapshot_date'], name='ret_snap_tenant_date_idx')],
                'unique_together': {('tenant', 'snapshot_date')},
            },
        ),
    ]
