# Generated by Django 5.2.10 on 2026-10-07 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0002_tenantretentiondailysnapshot'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientretentionmetrics',
            name='ai_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientretentionmetrics',
            name='ai_risk_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated plain-language explanation of churn risk and recommended staff action'),
        ),
        migrations.AddField(
            model_name='clientretentionmetrics',
            name='at_risk_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue at stake if this client is HIGH or CRITICAL risk', max_digits=10),
        ),
        migrations.AddField(
            model_name='clientretentionmetrics',
            name='estimated_monthly_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Projected monthly recurring or package value for this client', max_digits=10),
        ),
        migrations.AddField(
            model_name='clientretentionmetrics',
            name='failed_payments_last_90d',
            field=models.PositiveIntegerField(default=0, help_text='Count of failed payment attempts in the last 90 days'),
        ),
        migrations.AddField(
            model_name='clientretentionmetrics',
            name='is_high_value',
            field=models.BooleanField(db_index=True, default=False, help_text='Big Spender / High-Value customer flag'),
        ),
        migrations.AddIndex(
            model_name='clientretentionmetrics',
            index=models.Index(fields=['tenant', 'is_high_value'], name='ret_metric_high_val_idx'),
        ),
    ]
