# Generated by Django 5.2.10 on 2026-10-07 13:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_deliveryrecord_notificationautomation_and_more'),
        ('retention', '0003_clientretentionmetrics_ai_evaluated_at_and_more'),
        ('scheduling', '0019_booking_no_show_at_and_more'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionCampaignTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('trigger_type', models.CharField(choices=[('inactivity', 'Inactivity'), ('failed_payment', 'Failed Payment'), ('package_expiry', 'Package Expiry'), ('custom_segment', 'Custom Segment')], default='inactivity', max_length=30)),
                ('trigger_value', models.IntegerField(default=0, help_text='Milestone or offset value (e.g. 14 for days inactive, or 7 for days before expiry)')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], default='email', max_length=20)),
                ('template_subject', models.CharField(blank=True, default='', max_length=255)),
                ('template_body', models.TextField()),
                ('use_ai_personalization', models.BooleanField(default=False, help_text='Whether to generate LLM-synthesized winback copy tailored to individual risk factors')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='retention.savedsegment')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Retention Campaign Trigger',
                'verbose_name_plural': 'Retention Campaign Triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionCampaignActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('sent', 'Sent'), ('clicked', 'Clicked'), ('converted', 'Converted')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('ai_generated_body', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_action_logs', to=settings.AUTH_USER_MODEL)),
                ('conversion_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_action_logs', to='scheduling.booking')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='retention.retentioncampaigntrigger')),
            ],
            options={
                'verbose_name': 'Retention Campaign Action Log',
                'verbose_name_plural': 'Retention Campaign Action Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionConversionAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_event', models.CharField(default='booking_checkin', max_length=50)),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('converted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='retention.retentioncampaignactionlog')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_attributions', to='scheduling.booking')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_attributions', to='notifications.notificationcampaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_attributions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_attributions', to='scheduling.payment')),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Retention Conversion Attribution',
                'verbose_name_plural': 'Retention Conversion Attributions',
                'ordering': ['-converted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='retentioncampaigntrigger',
            index=models.Index(fields=['tenant', 'is_active', 'trigger_type'], name='ret_trig_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='retentioncampaignactionlog',
            index=models.Index(fields=['tenant', 'client', 'trigger', 'action_type'], name='ret_act_cl_trig_idx'),
        ),
        migrations.AddIndex(
            model_name='retentioncampaignactionlog',
            index=models.Index(fields=['tenant', 'sent_at'], name='ret_act_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionconversionattribution',
            index=models.Index(fields=['tenant', 'client', 'converted_at'], name='ret_attr_cl_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionconversionattribution',
            index=models.Index(fields=['tenant', 'action_log'], name='ret_attr_act_log_idx'),
        ),
    ]
