# Generated by Django 5.2.10 on 2026-10-07 14:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0004_retentioncampaigntrigger_retentioncampaignactionlog_and_more'),
        ('tenants', '0006_tenant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBusinessInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('executive_summary', models.TextField(help_text='Plain-language LLM executive summary of weekly performance')),
                ('revenue_insights', models.JSONField(blank=True, default=dict, help_text='AI notes on MRR, package spend, and attributed conversion revenue')),
                ('retention_insights', models.JSONField(blank=True, default=dict, help_text='AI notes on churn rate, attendance deltas, and at-risk cohort transitions')),
                ('recommended_actions', models.JSONField(blank=True, default=list, help_text='Prioritized operational and marketing interventions for studio staff')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Weekly Business Insight',
                'verbose_name_plural': 'Weekly Business Insights',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['tenant', '-week_start'], name='ret_insight_tenant_week_idx')],
                'unique_together': {('tenant', 'week_start')},
            },
        ),
    ]
