# Generated by Django 5.2 on 2025-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0002_rename_author_post_posted_by_post_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="posted_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
