# Generated by Django 5.2 on 2025-05-05 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0003_alter_post_posted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="polloption",
            name="post",
        ),
        migrations.RemoveField(
            model_name="polloption",
            name="option_text",
        ),
        migrations.AddField(
            model_name="polloption",
            name="text",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="polloption",
            name="votes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("likes_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "comments_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                (
                    "internal_deep_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "visible_to_staff",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "visible_to_clients",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("image", models.ImageField(upload_to="photos/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("likes_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "comments_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                (
                    "internal_deep_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "visible_to_staff",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "visible_to_clients",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_multiple_choice", models.BooleanField(default=False)),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="polls",
                        to="socialnetwork.polloption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("likes_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "comments_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                (
                    "internal_deep_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "visible_to_staff",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "visible_to_clients",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_votes",
                        to="socialnetwork.polloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_votes",
                        to="socialnetwork.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "poll", "option")},
            },
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
