# Generated by Django 5.2 on 2025-05-06 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0004_alter_like_unique_together_remove_like_post_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="options",
        ),
        migrations.AddField(
            model_name="polloption",
            name="poll",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="socialnetwork.poll",
            ),
            preserve_default=False,
        ),
    ]
