# Generated by Django 5.2 on 2025-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialnetwork", "0005_remove_poll_options_polloption_poll"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polloption",
            name="poll",
        ),
        migrations.AddField(
            model_name="poll",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="polls",
                to="socialnetwork.polloption",
            ),
        ),
    ]
