# Generated by Django 4.2.21 on 2025-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_remove_photo_is_active_remove_poll_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
