# Generated by Django 4.2.21 on 2025-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_add_location_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comments_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='comments_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='comments_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
