# Generated by Django 4.2.21 on 2025-05-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_photo_comments_enabled_poll_comments_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comments_enabled',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='comments_enabled',
        ),
        migrations.RemoveField(
            model_name='video',
            name='comments_enabled',
        ),
    ]
