# Generated by Django 4.2.21 on 2023-05-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_mediagroup_photo_media_group_video_media_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='media_group',
        ),
        migrations.RemoveField(
            model_name='video',
            name='media_group',
        ),
        migrations.DeleteModel(
            name='MediaGroup',
        ),
    ]
