# Generated by Django 5.2.1 on 2025-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0013_mediagroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=2400, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='caption',
            field=models.CharField(blank=True, max_length=2400, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(blank=True, max_length=2400, null=True),
        ),
    ]
