# Generated by Django 5.2.1 on 2025-10-27 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('cholesterol', models.CharField(blank=True, max_length=50, null=True)),
                ('saturated_fat', models.CharField(blank=True, max_length=50, null=True)),
                ('fiber', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_qty', models.CharField(blank=True, max_length=24, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('sodium', models.CharField(blank=True, max_length=50, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
