# Generated by Django 5.2.1 on 2025-10-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsuggestion',
            name='description',
        ),
    ]
