# Generated by Django 5.2.1 on 2025-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0003_staffrecipe_staffrecipeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecipe',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
