# Generated by Django 5.2.1 on 2025-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0004_alter_staffrecipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsuggestion',
            name='brand_name_item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='serving_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='sugars',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
