# Generated by Django 5.2.1 on 2025-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0005_foodsuggestion_brand_name_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
