# Generated by Django 5.2.1 on 2025-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0006_staffrecipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
