# Generated by Django 5.2.1 on 2025-10-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0007_alter_staffrecipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrecipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='staffrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
