# Generated by Django 5.2.1 on 2025-10-29 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0008_remove_staffrecipe_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrecipe',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffrecipe',
            name='title',
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='nix_brand_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='nix_item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='potassium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='serving_weight_grams',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodsuggestion',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('serving_qty', models.CharField(blank=True, max_length=24, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_weight_grams', models.CharField(blank=True, max_length=50, null=True)),
                ('cholesterol', models.CharField(blank=True, max_length=50, null=True)),
                ('sodium', models.CharField(blank=True, max_length=50, null=True)),
                ('sugars', models.CharField(blank=True, max_length=50, null=True)),
                ('potassium', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('staff_recipe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recipe_links', to='food_logger.staffrecipeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_recipe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
