# Generated by Django 5.2.1 on 2025-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0009_remove_staffrecipe_staff_remove_staffrecipe_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecipeitem',
            name='fiber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='nix_brand_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='nix_item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='saturated_fat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
