# Generated by Django 5.2.1 on 2025-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0010_staffrecipeitem_fiber_staffrecipeitem_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecipeitem',
            name='serving_info',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
