# Generated by Django 5.2.1 on 2025-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0011_staffrecipeitem_serving_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipeitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
