# Generated by Django 5.2.1 on 2025-11-03 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0012_alter_userrecipeitem_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.FloatField(default=2000)),
                ('daily_protein', models.FloatField(default=150)),
                ('daily_carbs', models.FloatField(default=250)),
                ('daily_fat', models.FloatField(default=70)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
