# Generated by Django 5.2.1 on 2025-11-03 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0013_usernutritiongoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('cholesterol', models.CharField(blank=True, max_length=50, null=True)),
                ('saturated_fat', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_weight_grams', models.CharField(blank=True, max_length=50, null=True)),
                ('fiber', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_qty', models.CharField(blank=True, max_length=24, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('potassium', models.CharField(blank=True, max_length=50, null=True)),
                ('sodium', models.CharField(blank=True, max_length=50, null=True)),
                ('sugars', models.CharField(blank=True, max_length=50, null=True)),
                ('directions', models.TextField(blank=True, null=True)),
                ('brand_name_item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=50, null=True)),
                ('locale', models.CharField(blank=True, max_length=50, null=True)),
                ('nix_item_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nix_brand_id', models.CharField(blank=True, max_length=50, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_logger.custommeal')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_meals', to='food_logger.foodsuggestion')),
            ],
        ),
    ]
