# Generated by Django 5.2.1 on 2025-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0014_custommeal_mealitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommeal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
