# Generated by Django 5.2.1 on 2025-11-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0015_alter_custommeal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
