# Generated by Django 5.2.1 on 2025-11-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0016_alter_mealitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipeitem',
            name='staff_recipe_item',
        ),
    ]
