# Generated by Django 5.2.1 on 2025-11-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0017_remove_userrecipeitem_staff_recipe_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommeal',
            old_name='description',
            new_name='directions',
        ),
        migrations.RemoveField(
            model_name='custommeal',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='suggestion',
        ),
    ]
