# Generated by Django 5.2.1 on 2025-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0018_rename_description_custommeal_directions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='serving_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
