# Generated by Django 5.2.1 on 2025-11-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0020_loggedmeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedmeal',
            old_name='fat',
            new_name='fats',
        ),
    ]
