# Generated by Django 5.2.1 on 2025-11-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0021_rename_fat_loggedmeal_fats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedmeal',
            old_name='calories',
            new_name='total_calories',
        ),
        migrations.RenameField(
            model_name='loggedmeal',
            old_name='carbs',
            new_name='total_carbs',
        ),
        migrations.RenameField(
            model_name='loggedmeal',
            old_name='fats',
            new_name='total_fats',
        ),
        migrations.RenameField(
            model_name='loggedmeal',
            old_name='protein',
            new_name='total_protein',
        ),
    ]
