# Generated by Django 5.2.1 on 2025-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0022_rename_calories_loggedmeal_total_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutritiongoal',
            name='base_calories',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
