# Generated by Django 5.2.1 on 2025-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0023_usernutritiongoal_base_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutritiongoal',
            name='base_goal',
            field=models.FloatField(default=0),
        ),
    ]
