# Generated by Django 5.2.1 on 2025-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0024_usernutritiongoal_base_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipeitem',
            name='serving_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
