# Generated by Django 5.2.1 on 2025-11-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0025_userrecipeitem_serving_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedmeal',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='loggedmeal',
            name='custom_meal',
        ),
        migrations.RemoveField(
            model_name='loggedmeal',
            name='staff_recipe',
        ),
        migrations.RemoveField(
            model_name='loggedmeal',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='loggedmeal',
            name='user_recipe_item',
        ),
        migrations.CreateModel(
            name='LoggedMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('logged_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_logger.loggedmeal')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_meal_items', to='food_logger.mealitem')),
                ('staff_recipe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_staff_items', to='food_logger.staffrecipeitem')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_suggestion_items', to='food_logger.foodsuggestion')),
                ('user_recipe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_user_recipe_items', to='food_logger.userrecipeitem')),
            ],
        ),
    ]
