# Generated by Django 5.2.1 on 2025-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0026_rename_date_loggedmeal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipeitem',
            name='fiber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecipeitem',
            name='locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecipeitem',
            name='nix_brand_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecipeitem',
            name='nix_item_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecipeitem',
            name='saturated_fat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecipeitem',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrecipeitem',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usernutritiongoal',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
