# Generated by Django 5.2.1 on 2025-11-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0027_userrecipeitem_fiber_userrecipeitem_locale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernutritiongoal',
            name='base_calories',
        ),
        migrations.AlterField(
            model_name='usernutritiongoal',
            name='base_goal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usernutritiongoal',
            name='daily_calories',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usernutritiongoal',
            name='daily_carbs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usernutritiongoal',
            name='daily_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usernutritiongoal',
            name='daily_protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
