# Generated by Django 5.2.1 on 2025-11-05 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0028_remove_usernutritiongoal_base_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernutritiongoal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usernutritiongoal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
