# Generated by Django 5.2.1 on 2025-11-05 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0029_remove_usernutritiongoal_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernutritiongoal',
            unique_together={('user', 'date')},
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('serving_qty', models.CharField(blank=True, max_length=24, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('serving_info', models.CharField(blank=True, max_length=50, null=True)),
                ('potassium', models.CharField(blank=True, max_length=50, null=True)),
                ('sodium', models.CharField(blank=True, max_length=50, null=True)),
                ('sugars', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_name_item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=50, null=True)),
                ('locale', models.CharField(blank=True, max_length=50, null=True)),
                ('nix_item_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nix_brand_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
