# Generated by Django 5.2.1 on 2025-11-05 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0031_alter_usernutritiongoal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutritiongoal',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
