# Generated by Django 5.2.1 on 2025-11-05 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0032_alter_usernutritiongoal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfood',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='loggedmealitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_food_items', to='food_logger.customfood'),
        ),
    ]
