# Generated by Django 5.2.1 on 2025-11-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0033_customfood_date_loggedmealitem_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfood',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customfood',
            name='fiber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customfood',
            name='saturated_fat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customfood',
            name='serving_weight_grams',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
