# Generated by Django 5.2.1 on 2025-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0034_customfood_cholesterol_customfood_fiber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfood',
            name='is_custom_food',
            field=models.BooleanField(default=False),
        ),
    ]
