# Generated by Django 5.2.1 on 2025-11-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0036_favoritestaffrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecipeitem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
