# Generated by Django 5.2.1 on 2025-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0037_alter_staffrecipeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecipeitem',
            name='img',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
