# Generated by Django 5.2.1 on 2025-11-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0038_staffrecipeitem_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernutritiongoal',
            unique_together=set(),
        ),
    ]
