# Generated by Django 5.2.1 on 2025-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0039_alter_usernutritiongoal_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrecipeitem',
            name='img',
        ),
        migrations.AddField(
            model_name='staffrecipeitem',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
