# Generated by Django 5.2.1 on 2025-11-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0040_remove_staffrecipeitem_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecipeitem',
            name='image_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
