# Generated by Django 5.2.1 on 2025-11-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0041_alter_staffrecipeitem_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrecipeitem',
            name='image_file',
        ),
    ]
