# Generated by Django 5.2.1 on 2025-11-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0042_remove_staffrecipeitem_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmealitem',
            name='logged_serving_qty',
            field=models.FloatField(blank=True, max_length=24, null=True),
        ),
    ]
