# Generated by Django 5.2.1 on 2025-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0043_loggedmealitem_logged_serving_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmeal',
            name='meal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
