# Generated by Django 5.2.1 on 2025-12-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0044_loggedmeal_meal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedmeal',
            name='meal_name',
        ),
    ]
