# Generated by Django 5.2.1 on 2025-12-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0045_remove_loggedmeal_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='brand_name_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodsuggestion',
            name='brand_name_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='brand_name_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
