# Generated by Django 5.2.1 on 2025-12-05 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0046_alter_customfood_brand_name_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedmeal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
