# Generated by Django 5.2.1 on 2026-03-26 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0047_alter_loggedmeal_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(help_text='e.g., Blood Pressure, Muscle Recovery', max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 10mg, 2 scoops', max_length=100)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Twice a Day', 'Twice a Day'), ('Weekly', 'Weekly'), ('As Needed', 'As Needed'), ('Other', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if taken indefinitely', null=True)),
                ('is_currently_active', models.BooleanField(default=True)),
                ('prescribed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='e.g., Take with food', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
