# Generated by Django 5.2.10 on 2026-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_logger', '0048_usermedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutritiongoal',
            name='daily_water',
            field=models.FloatField(blank=True, default=0, help_text='Daily water goal in ml', null=True),
        ),
    ]
