# Generated by Django 5.2.10 on 2026-08-08 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenants', '0006_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Email')], max_length=10)),
                ('email_address', models.EmailField(blank=True, help_text='Set for email channel delivery records', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, help_text="Provider's message/delivery ID", max_length=255)),
                ('provider_status', models.CharField(blank=True, help_text='Provider-reported status', max_length=100)),
                ('error_code', models.CharField(blank=True, help_text='Error code on failure (e.g. UNREGISTERED)', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Human-readable error on failure')),
                ('provider_response_raw', models.JSONField(blank=True, default=dict, help_text='Raw provider response. For debugging only — prune according to retention policy.')),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery Record',
                'verbose_name_plural': 'Delivery Records',
            },
        ),
        migrations.CreateModel(
            name='NotificationAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('event_trigger', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('waitlist_offered', 'Waitlist Spot Offered'), ('appointment_reminder', 'Appointment Reminder'), ('workout_assigned', 'Workout Assigned'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('membership_expiring', 'Membership Expiring'), ('class_reminder_24h', 'Class Reminder (24h)'), ('class_reminder_1h', 'Class Reminder (1h)'), ('session_cancelled', 'Session Cancelled'), ('substitute_request_broadcast', 'Substitute Request Broadcast')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('lead_time_minutes', models.PositiveIntegerField(blank=True, help_text='For time-based reminders: minutes before event to send. e.g. 60 = 1 hour before.', null=True)),
            ],
            options={
                'verbose_name': 'Notification Automation',
                'verbose_name_plural': 'Notification Automations',
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('CLASS', 'Class'), ('APPOINTMENT', 'Appointment'), ('BOOKING', 'Booking'), ('WAITLIST', 'Waitlist'), ('WORKOUT', 'Workout'), ('MEMBERSHIP', 'Membership'), ('PAYMENT', 'Payment'), ('NUTRITION', 'Nutrition'), ('INVENTORY', 'Inventory'), ('SOCIAL', 'Social'), ('MAINTENANCE', 'Maintenance'), ('EMERGENCY', 'Emergency'), ('SYSTEM', 'System')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('CAMPAIGN', 'Campaign'), ('AUTOMATION', 'Automation')], default='CAMPAIGN', help_text='Origin: CAMPAIGN (owner-created), AUTOMATION (rule-triggered), SYSTEM (platform event)', max_length=15)),
                ('delivery_policy', models.CharField(choices=[('PUSH_ONLY', 'Push Only'), ('PUSH_AND_EMAIL', 'Push and Email')], default='PUSH_ONLY', help_text='Derived by ChannelPolicyEngine from priority and template. Not directly user-settable.', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('PARTIALLY_SENT', 'Partially Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15)),
                ('audience_type', models.CharField(choices=[('ALL_CLIENTS', 'All Clients'), ('ALL_STAFF', 'All Staff'), ('ALL_TRAINERS', 'All Trainers'), ('ALL_MANAGERS', 'All Managers'), ('SPECIFIC_USERS', 'Specific Users'), ('GROUP', 'Notification Group'), ('CLASS_BOOKINGS', 'Class Bookings'), ('CLASS_WAITLIST', 'Class Waitlist'), ('TRAINER_CLIENTS', 'Trainer Clients'), ('APPOINTMENT_ATTENDEES', 'Appointment Attendees'), ('DYNAMIC_FILTER', 'Dynamic Filter')], default='ALL_CLIENTS', max_length=25)),
                ('audience_entity_id', models.UUIDField(blank=True, help_text='Entity ID for CLASS_BOOKINGS, CLASS_WAITLIST, TRAINER_CLIENTS, APPOINTMENT_ATTENDEES', null=True)),
                ('audience_filter', models.JSONField(blank=True, default=dict, help_text='Dynamic filter config for DYNAMIC_FILTER audience type')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled delivery time (UTC). null = immediate on send().', null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, help_text='Next scheduled execution time (UTC). Updated after each recurring run.', null=True)),
                ('bypass_quiet_hours', models.BooleanField(default=False, help_text='If True, ignores quiet hours. CRITICAL always bypasses if tenant setting allows.')),
                ('action_payload', models.JSONField(blank=True, default=dict, help_text='Structured deep-link payload. e.g. {"action": "OPEN_WORKOUT", "entity_type": "workout", "entity_id": "123"}')),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('push_sent_count', models.PositiveIntegerField(default=0)),
                ('push_failed_count', models.PositiveIntegerField(default=0)),
                ('email_sent_count', models.PositiveIntegerField(default=0)),
                ('email_failed_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for potential cancellation via revoke()', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Prevents duplicate campaign delivery on Celery retries', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Notification Campaign',
                'verbose_name_plural': 'Notification Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Notification Group',
                'verbose_name_plural': 'Notification Groups',
            },
        ),
        migrations.CreateModel(
            name='NotificationGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Group Member',
                'verbose_name_plural': 'Notification Group Members',
            },
        ),
        migrations.CreateModel(
            name='NotificationInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('CLASS', 'Class'), ('APPOINTMENT', 'Appointment'), ('BOOKING', 'Booking'), ('WAITLIST', 'Waitlist'), ('WORKOUT', 'Workout'), ('MEMBERSHIP', 'Membership'), ('PAYMENT', 'Payment'), ('NUTRITION', 'Nutrition'), ('INVENTORY', 'Inventory'), ('SOCIAL', 'Social'), ('MAINTENANCE', 'Maintenance'), ('EMERGENCY', 'Emergency'), ('SYSTEM', 'System')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('CAMPAIGN', 'Campaign'), ('AUTOMATION', 'Automation')], default='CAMPAIGN', max_length=15)),
                ('delivery_policy', models.CharField(choices=[('PUSH_ONLY', 'Push Only'), ('PUSH_AND_EMAIL', 'Push and Email')], default='PUSH_ONLY', max_length=15)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Notification Inbox Item',
                'verbose_name_plural': 'Notification Inbox Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Per-notification-type opt-in state. Keys are NotificationType values.')),
                ('push_enabled', models.BooleanField(default=True, help_text='User-level push channel toggle')),
                ('email_enabled', models.BooleanField(default=True, help_text='User-level email channel toggle')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_of_week', models.JSONField(help_text="List of weekday strings, e.g. ['monday', 'wednesday', 'friday']")),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('send_time', models.TimeField(help_text="Time of day to send, in the tenant's configured timezone")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Recurrence Rule',
                'verbose_name_plural': 'Notification Recurrence Rules',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('CLASS', 'Class'), ('APPOINTMENT', 'Appointment'), ('BOOKING', 'Booking'), ('WAITLIST', 'Waitlist'), ('WORKOUT', 'Workout'), ('MEMBERSHIP', 'Membership'), ('PAYMENT', 'Payment'), ('NUTRITION', 'Nutrition'), ('INVENTORY', 'Inventory'), ('SOCIAL', 'Social'), ('MAINTENANCE', 'Maintenance'), ('EMERGENCY', 'Emergency'), ('SYSTEM', 'System')], max_length=20)),
                ('title_template', models.CharField(help_text='Supports {{variable}} substitution', max_length=255)),
                ('body_template', models.TextField(help_text='Supports {{variable}} substitution')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('is_critical', models.BooleanField(default=False, help_text='If True, forces PUSH_AND_EMAIL delivery. Set for payment failures, emergencies.')),
                ('is_user_configurable', models.BooleanField(default=True, help_text='If False, user preference opt-out is ignored. Use for mandatory notifications.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='TenantNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='UTC', help_text="Tenant timezone for scheduled notifications (e.g. 'Asia/Karachi')", max_length=100)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet window (e.g. 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet window (e.g. 07:00)', null=True)),
                ('quiet_hours_bypass_critical', models.BooleanField(default=True, help_text='If True, CRITICAL priority notifications bypass quiet hours')),
                ('max_campaigns_per_day', models.PositiveIntegerField(default=50, help_text='Maximum campaigns a tenant can send per day')),
            ],
            options={
                'verbose_name': 'Tenant Notification Settings',
                'verbose_name_plural': 'Tenant Notification Settings',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fcmdevice',
            name='device_type',
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Last time this device was seen (auto-updated on save)'),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='platform',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text='Device platform', max_length=20, null=True),
        ),
        migrations.RunSQL("DELETE FROM notifications_fcmdevice;"),
        migrations.AddField(
            model_name='fcmdevice',
            name='tenant',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this token is still valid. Set to False on UNREGISTERED error.'),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique device identifier (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='registration_id',
            field=models.TextField(help_text='Firebase device registration token', verbose_name='Registration Token'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['tenant', 'user', 'active'], name='notificatio_tenant__f89a8f_idx'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_records', to='notifications.fcmdevice'),
        ),
        migrations.AddField(
            model_name='notificationautomation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationautomation',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='audience_users',
            field=models.ManyToManyField(blank=True, help_text='Used when audience_type=SPECIFIC_USERS', related_name='targeted_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='audience_group',
            field=models.ForeignKey(blank=True, help_text='Used when audience_type=GROUP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='notifications.notificationgroup'),
        ),
        migrations.AddField(
            model_name='notificationgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='notifications.notificationgroup'),
        ),
        migrations.AddField(
            model_name='notificationgroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationinbox',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Source campaign, if this was a broadcast. Null for automated/system notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_items', to='notifications.notificationcampaign'),
        ),
        migrations.AddField(
            model_name='notificationinbox',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_inbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationinbox',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='inbox_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='notifications.notificationinbox'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrecurrencerule',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='notifications.notificationrecurrencerule'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationautomation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automations', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='tenantnotificationsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='tenants.tenant'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AlterUniqueTogether(
            name='notificationgroup',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationgroupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_af31eb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['tenant', 'recipient', 'created_at'], name='notificatio_tenant__10cc83_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['tenant', 'source'], name='notificatio_tenant__ae579b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationinbox',
            index=models.Index(fields=['tenant', 'notification_type'], name='notificatio_tenant__e8faab_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['inbox_item', 'channel', 'status'], name='notificatio_inbox_i_8b31c4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'notification_type', 'is_active'], name='notificatio_tenant__df852d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['tenant', 'status'], name='notificatio_tenant__009fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['tenant', 'source'], name='notificatio_tenant__679652_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['tenant', 'notification_type'], name='notificatio_tenant__bea33c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['next_run_at', 'status'], name='notificatio_next_ru_bab4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__604304_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationautomation',
            index=models.Index(fields=['tenant', 'event_trigger', 'is_active'], name='notificatio_tenant__0c6eb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationautomation',
            unique_together={('tenant', 'event_trigger')},
        ),
    ]
